name: Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22.3.0
          token: ${{ github.token }}
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      
      # Test
      - run: npm run test
      - name: Code coverage
        uses: codecov/codecov-action@v4

      # CI
      - name: Version bump
        uses: phips28/gh-action-bump-version@v11.0.4
        with:
          target-branch: main
          commit-message: auto version bump

      # Build
      - run: npm run build
      
      # Publish
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
